name: CMake

on:
  push:
    branches: [ "main", 'releases/**' ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build-${{ matrix.os }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build-${{ matrix.os }} --config ${{env.BUILD_TYPE}}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: except-${{ matrix.os }}
          path: |
            ${{github.workspace}}/build-${{ matrix.os }}/libexception.*
            ${{github.workspace}}/except/*.hpp
      - name: Create Release
        if: startsWith( github.ref, 'release' )
        uses: fnkr/github-action-ghr@v1.3
      
